### ISSUE TITLE
Not working on Windows 11 (.exe + .vst3)

### ISSUE THREAD

**Issue by DomMcsweeney** [brummer10/neuralrecord#1]
.exe is not starting up on windows 11
.vst3 - it scans in Reaper, but when loading it Reaper closes unexpectedly without warning (when attempting to load it onto a track).   

Probably worth looking into!

**Comment by brummer10** [comment]
Thanks for reporting the issue. 
Unfortunately I didn't have a windows machine, so I could only guess. 
I found that I used  getenv("HOME"); on windows as well, that may be the culprit. I've implemented that now for windows as getenv("USERPROFILE");
It may work now, or not? You may try the latest release 
https://github.com/brummer10/neuralrecord/releases/tag/v0.1.2

If you try it, let me know the result. 
btw. the windows exe requires jackd as sound server and requires that  one of the plugs (vst3/LV2) have run one time before.
