### ISSUE TITLE
[Win] select the input and output

### ISSUE THREAD

**Issue by spunktsch** [brummer10/neuralrecord#3]
plugin should have a selection of inputs and outputs on the windows standalone version.

**Comment by brummer10** [comment]
Hi
I don't understand what you mean. NeuralRecord have one input and one output, that's all.
The output play back the input.wav file and the input record the looped back from it by delay the record time  for the roundtrip latency. 
I didn't have a windows machine, so I didn't really know how the standalone windows version behave.

**Comment by falkTX** [comment]
on systems without jack running, the dpf standalones will use the default audio interface, with audio input and midi disabled by default as that usually requires OS permissions for their use.
see https://github.com/DISTRHO/DPF/blob/main/distrho/DistrhoStandaloneUtils.hpp for how to manage this condition.

if using the default soundcard does not really work at all, then consider not shipping with standalones at all.

I have no intention to add device settings screens in dpf, that goes against the simplistic idea of it.

**Comment by brummer10** [comment]
The stand-alone version is anyway only meant as a fallback. Preferable is using the vst3 or the LV2 version. 
Therefore this issue will be closed now.
