### ISSUE TITLE
Crashing on M1 Mac 13.4.1 (c) 

### ISSUE THREAD

**Issue by mreed707** [brummer10/neuralrecord#4]
Trying to figure out to use this and have no experience using terminal.

Desktop standalone stated error no input signal and stops the process.

Unable to see VST3 plugin in Mac Logic Pro though its installed and seen in Plugin folder in Library.

Using an audio interface EVO 8 and managed to see output signal from output 1 of 4 channels available but unable to loop back to recorder.  

Only once when starting up desktop plugin have I seen it ask for permission to use microphone wwhich is when I started seeing the output signal.

I hope this makes some sense and now the recorder is crashing and problem report pasted below 

Translated Report (Full Report Below)
-------------------------------------

Process:               neuralrecord [2070]
Path:                  /Volumes/VOLUME/*/neuralrecord.app/Contents/MacOS/neuralrecord
Identifier:            studio.kx.distrho.neuralrecord
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-08 16:31:32.5678 +0100
OS Version:            macOS 13.4.1 (22F770820d)
Report Version:        12
Anonymous UUID:        DB9ACACB-6CC2-F6F4-2145-5772C5BF4456

Time Awake Since Boot: 22000 seconds

System Integrity Protection: enabled

Crashed Thread:        8

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000c8
Exception Codes:       0x0000000000000001, 0x00000000000000c8

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [2070]

VM Region Info: 0xc8 is not in any region.  Bytes before following region: 140722873335608
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file              7ffc98e08000-7ffca7f3c000 [241.2M] r-x/r-x SM=COW  ...t_id=b5aa1979

Thread 0::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff89b4d69a8 ???
1   libsystem_kernel.dylib        	    0x7ff80b89c5b2 mach_msg2_trap + 10
2   libsystem_kernel.dylib        	    0x7ff80b8aa72d mach_msg2_internal + 78
3   libsystem_kernel.dylib        	    0x7ff80b8a35e4 mach_msg_overwrite + 692
4   libsystem_kernel.dylib        	    0x7ff80b89c89a mach_msg + 19
5   CoreFoundation                	    0x7ff80b9b6a40 __CFRunLoopServiceMachPort + 145
6   CoreFoundation                	    0x7ff80b9b54cb __CFRunLoopRun + 1365
7   CoreFoundation                	    0x7ff80b9b491c CFRunLoopRunSpecific + 560
8   neuralrecord                  	       0x100e3f8e9 0x100e20000 + 129257

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc4a694 0x7ff7ffc46000 + 18068

Thread 2:
0   runtime                       	    0x7ff7ffc6887c 0x7ff7ffc46000 + 141436

Thread 3:: caulk.messenger.shared:17
0   ???                           	    0x7ff89b4d69a8 ???
1   libsystem_kernel.dylib        	    0x7ff80b89c52e semaphore_wait_trap + 10
2   caulk                         	    0x7ff81562f07e caulk::semaphore::timed_wait(double) + 150
3   caulk                         	    0x7ff81562ef9c caulk::concurrent::details::worker_thread::run() + 30
4   caulk                         	    0x7ff81562ecb0 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
5   libsystem_pthread.dylib       	    0x7ff80b8db1d3 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff80b8d6bd3 thread_start + 15

Thread 4:
0   ???                           	    0x7ff89b4d69a8 ???
1   libsystem_kernel.dylib        	    0x7ff80b89da1e __lseek + 10
2   neuralrecord                  	       0x100e95d42 0x100e20000 + 482626

Thread 5:
0   runtime                       	    0x7ff7ffc6887c 0x7ff7ffc46000 + 141436

Thread 6:: com.apple.audio.IOThread.client
0   ???                           	    0x7ff89b4d69a8 ???
1   libsystem_kernel.dylib        	    0x7ff80b89c5b2 mach_msg2_trap + 10
2   libsystem_kernel.dylib        	    0x7ff80b8aa72d mach_msg2_internal + 78
3   libsystem_kernel.dylib        	    0x7ff80b8a35e4 mach_msg_overwrite + 692
4   libsystem_kernel.dylib        	    0x7ff80b89c89a mach_msg + 19
5   CoreAudio                     	    0x7ff80dae6175 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
6   CoreAudio                     	    0x7ff80d9d06a1 HALC_ProxyIOContext::IOWorkLoop() + 4035
7   CoreAudio                     	    0x7ff80d9cf049 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 80
8   CoreAudio                     	    0x7ff80db3e946 HALB_IOThread::Entry(void*) + 72
9   libsystem_pthread.dylib       	    0x7ff80b8db1d3 _pthread_start + 125
10  libsystem_pthread.dylib       	    0x7ff80b8d6bd3 thread_start + 15

Thread 7:
0   runtime                       	    0x7ff7ffc6887c 0x7ff7ffc46000 + 141436

Thread 8 Crashed:
0   neuralrecord                  	       0x100f67771 0x100e20000 + 1341297
1   neuralrecord                  	       0x100f640fc 0x100e20000 + 1327356

Thread 8 crashed with X86 Thread State (64-bit):
  rax: 0x00007f9e1ef924a0  rbx: 0x00007f9e1ef923c0  rcx: 0x0000000000000000  rdx: 0x00000000000000c8
  rdi: 0x0000000000000000  rsi: 0x00007f9e1f02a0d0  rbp: 0x0000000000000000  rsp: 0x00000003064c0af0
   r8: 0x0000000000008e35   r9: 0x00000000000008e2  r10: 0x00007f9e1ef00000  r11: 0x00000000ffffc000
  r12: 0x00007f9e1f02a030  r13: 0x00007f9e1ef96830  r14: 0x00007f9e1f02a028  r15: 0x00007f9e1f02a370
  rip: <unavailable>       rfl: 0x0000000000000242
 tmp0: 0x0000000100f67747 tmp1: 0x0000000100f67747 tmp2: 0x000000010132ef38

Binary Images:
       0x2011f9000 -        0x201294fff dyld (*) <5db85b72-c63a-3182-91e5-5c942ec30e48> /usr/lib/dyld
    0x7ff7ffc46000 -     0x7ff7ffc75fff runtime (*) <c4d322c3-30c5-3c52-adb8-2fd12ec92bc0> /usr/libexec/rosetta/runtime
       0x1094f4000 -        0x109547fff libRosettaRuntime (*) <c8f25cdc-b334-3f67-bc30-50e9852f8da2> /Library/Apple/*/libRosettaRuntime
       0x100e20000 -        0x10112bfff studio.kx.distrho.neuralrecord (*) <b58aaef0-f0c5-3d4e-ad41-145fe7105c0a> /Volumes/VOLUME/*/neuralrecord.app/Contents/MacOS/neuralrecord
       0x109d46000 -        0x109d55fff libobjc-trampolines.dylib (*) <1d043270-56bc-35fb-bef3-b1ba8ecb9120> /usr/lib/libobjc-trampolines.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff80b89b000 -     0x7ff80b8d4ff7 libsystem_kernel.dylib (*) <eb4e80a0-99da-32dc-b9ad-394fbb50a0ac> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80b93a000 -     0x7ff80bdd4fff com.apple.CoreFoundation (6.9) <661e8471-af64-30f9-9ce3-40bdaeeec321> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81562d000 -     0x7ff815651ff3 com.apple.audio.caulk (1.0) <905c3d28-a423-35c6-8a02-c88ba83bc3f6> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7ff80b8d5000 -     0x7ff80b8e0fff libsystem_pthread.dylib (*) <8cb0b396-011f-31f2-8915-94cde1abae84> /usr/lib/system/libsystem_pthread.dylib
    0x7ff80d7f7000 -     0x7ff80dea8ff6 com.apple.audio.CoreAudio (5.0) <61b97c10-5b99-3184-b5b8-48f90b6eabc3> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=443.6M resident=0K(0%) swapped_out_or_unallocated=443.6M(100%)
Writable regions: Total=442.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=442.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                  768K        4 
CG image                            24K        6 
ColorSync                          104K        8 
CoreAnimation                     1072K       11 
CoreGraphics                        12K        2 
CoreUI image data                  672K        9 
Dispatch continuations            64.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                            94.2M       58 
MALLOC guard page                  192K        8 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                   1096K      271 
Rosetta IndirectBranch             512K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               160K       16 
Rosetta Thread Context             160K       16 
STACK GUARD                         12K        3 
Stack                             11.6M        8 
Stack Guard                       56.0M        5 
VM_ALLOCATE                        9.8M       17 
VM_ALLOCATE (reserved)             104K        2         reserved VM address space (unallocated)
__CTF                               824        1 
__DATA                            17.7M      326 
__DATA_CONST                      15.2M      196 
__DATA_DIRTY                       744K      112 
__FONT_DATA                        2352        1 
__LINKEDIT                       171.6M        9 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2010K        2 
__TEXT                           272.0M      345 
dyld private memory                260K        2 
mapped file                        4.3G     1305 
shared memory                      828K       16 
unshared pmap                     6560K        5 
===========                     =======  ======= 
TOTAL                              5.3G     2775 
TOTAL, minus reserved VM space     5.2G     2775 

-----------
Full Report
-----------

{"app_name":"neuralrecord","timestamp":"2023-09-08 16:31:33.00 +0100","app_version":"","slice_uuid":"b58aaef0-f0c5-3d4e-ad41-145fe7105c0a","build_version":"","platform":1,"bundleID":"studio.kx.distrho.neuralrecord","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4.1 (22F770820d)","roots_installed":0,"name":"neuralrecord","incident_id":"11F35BA6-EE0A-4E94-AEDF-D3CE9FC2A4C1"}
{
  "uptime" : 22000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "coalitionID" : 1848,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F770820d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-08 16:31:32.5678 +0100",
  "incident" : "11F35BA6-EE0A-4E94-AEDF-D3CE9FC2A4C1",
  "pid" : 2070,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-08 16:30:33.2404 +0100",
  "procStartAbsTime" : 543370434190,
  "procExitAbsTime" : 544794156779,
  "procName" : "neuralrecord",
  "procPath" : "\/Volumes\/VOLUME\/*\/neuralrecord.app\/Contents\/MacOS\/neuralrecord",
  "bundleInfo" : {"CFBundleIdentifier":"studio.kx.distrho.neuralrecord"},
  "storeInfo" : {"deviceIdentifierForVendor":"9ED2B0DC-8410-5EC1-8345-DFDFC9DA0205","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "studio.kx.distrho.neuralrecord",
  "crashReporterKey" : "DB9ACACB-6CC2-F6F4-2145-5772C5BF4456",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "vmRegionInfo" : "0xc8 is not in any region.  Bytes before following region: 140722873335608\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file              7ffc98e08000-7ffca7f3c000 [241.2M] r-x\/r-x SM=COW  ...t_id=b5aa1979",
  "exception" : {"codes":"0x0000000000000001, 0x00000000000000c8","rawCodes":[1,200],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000000c8"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":2070},
  "vmregioninfo" : "0xc8 is not in any region.  Bytes before following region: 140722873335608\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file              7ffc98e08000-7ffca7f3c000 [241.2M] r-x\/r-x SM=COW  ...t_id=b5aa1979",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 8,
  "threads" : [{"id":157092,"queue":"com.apple.main-thread","frames":[{"imageOffset":140705734158760,"imageIndex":5},{"imageOffset":5554,"symbol":"mach_msg2_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":63277,"symbol":"mach_msg2_internal","symbolLocation":78,"imageIndex":6},{"imageOffset":34276,"symbol":"mach_msg_overwrite","symbolLocation":692,"imageIndex":6},{"imageOffset":6298,"symbol":"mach_msg","symbolLocation":19,"imageIndex":6},{"imageOffset":510528,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":145,"imageIndex":7},{"imageOffset":505035,"symbol":"__CFRunLoopRun","symbolLocation":1365,"imageIndex":7},{"imageOffset":502044,"symbol":"CFRunLoopRunSpecific","symbolLocation":560,"imageIndex":7},{"imageOffset":129257,"imageIndex":3}]},{"id":157120,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18068,"imageIndex":1}]},{"id":157123,"frames":[{"imageOffset":141436,"imageIndex":1}]},{"id":157125,"name":"caulk.messenger.shared:17","frames":[{"imageOffset":140705734158760,"imageIndex":5},{"imageOffset":5422,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":8318,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":150,"imageIndex":8},{"imageOffset":8092,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":30,"imageIndex":8},{"imageOffset":7344,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":41,"imageIndex":8},{"imageOffset":25043,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":9},{"imageOffset":7123,"symbol":"thread_start","symbolLocation":15,"imageIndex":9}]},{"id":157207,"frames":[{"imageOffset":140705734158760,"imageIndex":5},{"imageOffset":10782,"symbol":"__lseek","symbolLocation":10,"imageIndex":6},{"imageOffset":482626,"imageIndex":3}]},{"id":157220,"frames":[{"imageOffset":141436,"imageIndex":1}]},{"id":157617,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":140705734158760,"imageIndex":5},{"imageOffset":5554,"symbol":"mach_msg2_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":63277,"symbol":"mach_msg2_internal","symbolLocation":78,"imageIndex":6},{"imageOffset":34276,"symbol":"mach_msg_overwrite","symbolLocation":692,"imageIndex":6},{"imageOffset":6298,"symbol":"mach_msg","symbolLocation":19,"imageIndex":6},{"imageOffset":3076469,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":111,"imageIndex":10},{"imageOffset":1939105,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":4035,"imageIndex":10},{"imageOffset":1933385,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":80,"imageIndex":10},{"imageOffset":3438918,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":72,"imageIndex":10},{"imageOffset":25043,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":9},{"imageOffset":7123,"symbol":"thread_start","symbolLocation":15,"imageIndex":9}]},{"id":157864,"frames":[{"imageOffset":141436,"imageIndex":1}]},{"triggered":true,"id":157958,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":0},"r12":{"value":140317101826096},"rosetta":{"tmp2":{"value":4315082552},"tmp1":{"value":4311119687},"tmp0":{"value":4311119687}},"rbx":{"value":140317101204416},"r8":{"value":36405},"r15":{"value":140317101826928},"r10":{"value":140317100605440},"rdx":{"value":200},"rdi":{"value":0},"r9":{"value":2274},"r13":{"value":140317101221936},"rflags":{"value":578},"rax":{"value":140317101204640},"rsp":{"value":12990548720},"r11":{"value":4294950912},"rcx":{"value":0},"r14":{"value":140317101826088},"rsi":{"value":140317101826256}},"frames":[{"imageOffset":1341297,"imageIndex":3},{"imageOffset":1327356,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8608780288,
    "size" : 638976,
    "uuid" : "5db85b72-c63a-3182-91e5-5c942ec30e48",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124709376,
    "size" : 196608,
    "uuid" : "c4d322c3-30c5-3c52-adb8-2fd12ec92bc0",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4451155968,
    "size" : 344064,
    "uuid" : "c8f25cdc-b334-3f67-bc30-50e9852f8da2",
    "path" : "\/Library\/Apple\/*\/libRosettaRuntime",
    "name" : "libRosettaRuntime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4309778432,
    "CFBundleIdentifier" : "studio.kx.distrho.neuralrecord",
    "size" : 3194880,
    "uuid" : "b58aaef0-f0c5-3d4e-ad41-145fe7105c0a",
    "path" : "\/Volumes\/VOLUME\/*\/neuralrecord.app\/Contents\/MacOS\/neuralrecord",
    "name" : "neuralrecord"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4459880448,
    "size" : 65536,
    "uuid" : "1d043270-56bc-35fb-bef3-b1ba8ecb9120",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703322189824,
    "size" : 237560,
    "uuid" : "eb4e80a0-99da-32dc-b9ad-394fbb50a0ac",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703322841088,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4829184,
    "uuid" : "661e8471-af64-30f9-9ce3-40bdaeeec321",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1977"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703487414272,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 151540,
    "uuid" : "905c3d28-a423-35c6-8a02-c88ba83bc3f6",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703322427392,
    "size" : 49152,
    "uuid" : "8cb0b396-011f-31f2-8915-94cde1abae84",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703355072512,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7020535,
    "uuid" : "61b97c10-5b99-3184-b5b8-48f90b6eabc3",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  }
],
  "sharedCache" : {
  "base" : 140703318294528,
  "size" : 21474836480,
  "uuid" : "a2b4f9fa-3654-3401-a9f8-42889611882d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=443.6M resident=0K(0%) swapped_out_or_unallocated=443.6M(100%)\nWritable regions: Total=442.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=442.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                  768K        4 \nCG image                            24K        6 \nColorSync                          104K        8 \nCoreAnimation                     1072K       11 \nCoreGraphics                        12K        2 \nCoreUI image data                  672K        9 \nDispatch continuations            64.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                            94.2M       58 \nMALLOC guard page                  192K        8 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                   1096K      271 \nRosetta IndirectBranch             512K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               160K       16 \nRosetta Thread Context             160K       16 \nSTACK GUARD                         12K        3 \nStack                             11.6M        8 \nStack Guard                       56.0M        5 \nVM_ALLOCATE                        9.8M       17 \nVM_ALLOCATE (reserved)             104K        2         reserved VM address space (unallocated)\n__CTF                               824        1 \n__DATA                            17.7M      326 \n__DATA_CONST                      15.2M      196 \n__DATA_DIRTY                       744K      112 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       171.6M        9 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2010K        2 \n__TEXT                           272.0M      345 \ndyld private memory                260K        2 \nmapped file                        4.3G     1305 \nshared memory                      828K       16 \nunshared pmap                     6560K        5 \n===========                     =======  ======= \nTOTAL                              5.3G     2775 \nTOTAL, minus reserved VM space     5.2G     2775 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "2bebad08c1126792cea55eee0d9c024dbe85661a",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62699e1ec1ff2978b47f6c3b",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "631f72d1de559130376df1fb"
      },
      "deploymentId" : 240000023
    },
    {
      "rolloutId" : "63a0a6cfd1cdb67d083006d0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    },
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    }
  ]
}
}

Model: Macmini9,1, BootROM 8422.121.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: VG2439 Series, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 12 2023 05:52:26 version 18.20.383.14.7.8.149 FWID 01-1469d19d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: EVO8
USB Device: USB31Bus
USB Device: USB30Bus
USB Device: USB2.0 Hub
USB Device: USB Keyboard
USB Device: USB2.0 Hub
USB Device: 2.4G Wireless Receiver
USB Device: Flash Card Reader/Writer
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by brummer10** [comment]
Hi
Thanks for reporting the issue. 
I've no idea what goes wrong on macOS. Unfortunately I haven't a machine with macOS, so I can't debug it myself. 
Seems I need some help here.

**Comment by brummer10** [comment]
I checked again the source code and found one issue which may be the culprit. I'm using unnamed semaphore which is POSIX but not implemented on macOS. I switched it to named semaphore so that it should work on macOS now as well.  
Please checkout the latest release here:
https://github.com/brummer10/neuralrecord/releases/latest
and let me know if it works.
Rgerads
hermann

**Comment by mreed707** [comment]
Hi,

sounds good, moving studio at the mo so max is not set up.  Will hopefully be able to test next week and get back to you as soon as poss.  Cheers
